# Generated by Django 5.2 on 2025-06-19 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_event"),
        ("wagtail_newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="newsletter_campaign",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="event",
            name="newsletter_recipients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_newsletter.newsletterrecipients",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="newsletter_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject for the newsletter. Defaults to page title if blank.",
                max_length=1000,
            ),
        ),
    ]
